[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = [
    'python3 -m pip install --upgrade pip setuptools wheel',
    'python3 -m pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python3 manage.py collectstatic --noinput --settings=config.settings.production'
]

[start]
cmd = 'python3 manage.py migrate --settings=config.settings.production && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120'
