[phases.setup]
nixPkgs = ['python311', 'postgresql', 'tesseract']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt',
    'playwright install --with-deps chromium'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput --settings=config.settings.production'
]

[start]
cmd = 'python manage.py migrate --settings=config.settings.production && gunicorn config.wsgi:application'
